### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by Kernald** [gusaul/grpcox#5]
There's currently no way to add gRPC metadata (https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md). It would be really nice to have that.

**Comment by RaphaelKellerAdc** [comment]
We would also be interested in that feature. We need to send the Authentication Header with the request.

**Comment by DuriDuri** [comment]
+1

**Comment by zxy198717** [comment]
+1

**Comment by fdcgr** [comment]
+1

**Comment by dpinart-uxland** [comment]
It seems @risoll added this feature but the PR is still pending to merge? any progress? any fork?

**Comment by gusaul** [comment]
yes its merged https://github.com/gusaul/grpcox/pull/20

**Comment by Sleepy-GH** [comment]
Has an updated container image with this feature been released on docker hub?
