### ISSUE TITLE
How to use HttpBasicAuth with docker？

### ISSUE THREAD

**Issue by likyh** [gusaul/grpcox#6]
I wanna add this server for my production server for debugging and finding error online, But it to danger to use without password. How can I add one ?

**Comment by likyh** [comment]
Thx

**Comment by gusaul** [comment]
dont put this grpcox on production, this tool intended to become development testing tools, if you want to test your grpc server on production, you can put this on your local computer, and make tunnel 
connection to your production server.

**Comment by likyh** [comment]
👌 Thx。 🌹
