### ISSUE TITLE
Cannot open web ui from docker

### ISSUE THREAD

**Issue by abakumov-v** [gusaul/grpcox#8]
Hi!

I'm try run application via docker-compose, but I cannot open the link http://localhost:6969/ in Google Chrome - I've get ERR_CONNECTION_REFUSED.

Docker container works fine - this is log output:

```
Service started on :6969
```

What I'm doing wrong?

**Comment by brettmorien** [comment]
I was able to get the web UI working by removing the quotes on the port mapping in docker-compose.yml.
`
      - 6969:6969
`

**Comment by fdcgr** [comment]
If you are using Mac try removing the following like from the docker-compose.yml:
```
network_mode: host
```

**Comment by abakumov-v** [comment]
@fdcgr Windows 10 )) sorry that I forgot 
to tell about environment

**Comment by aultokped** [comment]
solved
